name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Build and deploy to gh-pages
         uses: sauloxd/review-apps@v1.3.2
         with:
           build-cmd: 'yarn build'
           branch: 'gh-pages' # The branch you chose to be your github-pages source
           dist: 'public' # The dist folder where your "yarn build" command will place the build artifacts
